# -*- coding: utf-8 -*-
"""P1HW2_BradyRachel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kNa1SYFcPTnH0e1-NE5ieWp4VSIPHNf
"""

# Rachel Brady
# 2/27/2025
#P1HW2
# create a program that does some basic math on numbers that are entered

print("This program calculates and display travel expenses")

print()

print()

Budget=int(input("Enter Budget:"))
print()

traveldestination=input("Enter your travel destination:") # changed to string input
print()

gas=int(input("how much do you think you will spend on gas?"))
print()

accommodation=int(input("Approximately, how much will you need for accommodation/hotel?"))
print()

food=int(input("Last, how much do you need for food?"))
print()

print("-----Travel Expenses-----")
print()

location=str("travel destination")


print(f"Initial Budget:{Budget}") # Changed Initial_Budget to Budget

print()

gas=int(input("fuel:"))
accommodation=int(input("accommodation:"))
food=int(input("food:"))

print()

#Corrected f-string and variable name.
print(f"Remaining Balance:{Budget - gas - accommodation - food}") #Fixed syntax error in print statement.  Assumed you wanted to display remaining balance, not perform subtraction with a subtract variable which was not defined.