# -*- coding: utf-8 -*-
"""P1HW1_BradyRachel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIfrx5UJZVfLgDDBXcMmi_QUDvsgcGwU
"""

# Rachel Brady
# 2/27/2025
#P1HW1
#processes information collected and display results to user.

#Calculating Exponenets

print("------Calculating Exponenets-------")

print()

print()

#Get based value

basedValue=int(input("Enter an interger as the base value: "))

exponent=int(input("Enter an interger as the eponet: "))

print()

print()

print(basedValue,"raised to the power of", exponent, "is", basedValue ** exponent, "!!")

print()

print("-----Addition and subtraction-----")

print()

print()

interger=int(input("Enter a starting interger: "))

add=int(input("Enter an interger to add: "))

subtract=int(input("Enter an integer to subtract: "))

print(interger,"+",add,"-", subtract, "is equal to", interger + add - subtract)