# -*- coding: utf-8 -*-
"""P1LAB1_BradyRachel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SeIlrjzJ5DrjZvuxXjoLAcxl36a70Gtk
"""

# Rachel Brady
# 2/27/2025
#P1LAB1
#get input from the user and display output



# Get first name from user

firstName=input("Enter your first name: ")

# Get last name from user

lastName=input("Enter your last name: ")

# Display message to user

print("Hello," ,firstName,lastName+"! Welcome to CTI-110")